App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
    country:
      - NotBlank:
          groups: ['create', 'edit']
      - Length:
          min: 2
          max: 2
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']
    longtitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -180
          max: 180
          groups: ['create', 'edit']
App\Entity\Forecast:
  properties:
    date:
      - NotBlank:
          groups: ['create', 'edit']
    temperature:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -20
          max: 40
          groups: ['create', 'edit']
    cloudy:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: 0
          max: 100
          groups: ['create', 'edit']
    humidity:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: 0
          max: 100
          groups: ['create', 'edit']
    chanceOfPrecipitation:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: 0
          max: 100
          groups: ['create', 'edit']